/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.Jetsetmag.gui;

import edu.Jetsetmag.dao.ClientDAO;
import edu.Jetsetmag.entities.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author Me
 */
public class ClientFrame extends javax.swing.JFrame {

    /**
     * Creates new form AuthentificationClientFrame
     */
    public ClientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelLogin = new javax.swing.JLabel();
        TextLogin = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        TextPassword = new javax.swing.JTextField();
        btnInscription = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText("Login");
        jPanel1.add(LabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));
        jPanel1.add(TextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 150, -1));

        LabelPassword.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelPassword.setText("Password");
        jPanel1.add(LabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel1.add(TextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 150, -1));

        btnInscription.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnInscription.setText("S'inscrire");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 100, -1));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnLogin.setText("Se connecter");
        btnLogin.setToolTipText("");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundjdid.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(710, 360));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
  // TODO add your handling code here:
         if(TextLogin.getText().equals("")&&TextPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Veuillez entrer votre Login et Password ");
        }
        else{
        Client clt =new Client();
        String Login=TextLogin.getText();
        String Password=TextPassword.getText();
        clt.setLogin(Login);
        clt.setPassword(Password);
        ClientDAO clientDAO=new ClientDAO();
        Client clientResult = new Client();
        clientResult = clientDAO.findClientByLoginPassword(Login, Password);
        System.out.println("test" +clientResult.getLogin());
        if( clientResult.getLogin() == null)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"VEUILLEZ VERIFIER VOTRE LOGIN ET PASSWORD \n\n Si vous n'êtes pas inscrit inscrivez-vous ");
      
        }else
        {
        MenuClient b = new MenuClient();
        b.setVisible(true);
        this.setVisible(false); 
        }
        
        }
        
                         
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        // TODO add your handling code here:
         InscriClient isc = new InscriClient();
        isc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JTextField TextLogin;
    private javax.swing.JTextField TextPassword;
    private javax.swing.JButton btnInscription;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
