/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.Jetsetmag.gui;

import edu.Jetsetmag.dao.ClientDAO;
import edu.Jetsetmag.entities.Client;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Me
 */
public class InscriClient extends javax.swing.JFrame {

    /**
     * Creates new form InscriClient
     */
    public InscriClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Textbtn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelNom = new javax.swing.JLabel();
        LabelPrenom = new javax.swing.JLabel();
        LabelSexe = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        TextPrenom = new javax.swing.JTextField();
        TextNom = new javax.swing.JTextField();
        TextLogin = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        TextAge = new javax.swing.JTextField();
        TextNum = new javax.swing.JTextField();
        TextPassword = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnConfirmer = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        LabelNum = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 430));
        jPanel1.setLayout(null);

        LabelNom.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelNom.setForeground(new java.awt.Color(255, 255, 255));
        LabelNom.setText("Nom");
        jPanel1.add(LabelNom);
        LabelNom.setBounds(120, 80, 70, 22);

        LabelPrenom.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelPrenom.setForeground(new java.awt.Color(255, 255, 255));
        LabelPrenom.setText("Prénom");
        jPanel1.add(LabelPrenom);
        LabelPrenom.setBounds(120, 118, 80, 22);

        LabelSexe.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelSexe.setForeground(new java.awt.Color(255, 255, 255));
        LabelSexe.setText("Sexe");
        jPanel1.add(LabelSexe);
        LabelSexe.setBounds(120, 156, 60, 22);

        LabelAge.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelAge.setForeground(new java.awt.Color(255, 255, 255));
        LabelAge.setText("Age");
        jPanel1.add(LabelAge);
        LabelAge.setBounds(120, 194, 60, 22);

        LabelLogin.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText("Login");
        jPanel1.add(LabelLogin);
        LabelLogin.setBounds(120, 232, 70, 22);

        LabelPassword.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        LabelPassword.setText("Mot de passe");
        jPanel1.add(LabelPassword);
        LabelPassword.setBounds(120, 266, 120, 22);

        LabelEmail.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        LabelEmail.setText("Email");
        jPanel1.add(LabelEmail);
        LabelEmail.setBounds(120, 380, 110, 22);
        jPanel1.add(TextPrenom);
        TextPrenom.setBounds(351, 115, 223, 20);

        TextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomActionPerformed(evt);
            }
        });
        jPanel1.add(TextNom);
        TextNom.setBounds(351, 77, 223, 20);
        jPanel1.add(TextLogin);
        TextLogin.setBounds(351, 229, 223, 20);
        jPanel1.add(TextEmail);
        TextEmail.setBounds(351, 377, 223, 20);

        TextAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAgeActionPerformed(evt);
            }
        });
        jPanel1.add(TextAge);
        TextAge.setBounds(351, 191, 223, 20);
        jPanel1.add(TextNum);
        TextNum.setBounds(351, 339, 223, 20);
        jPanel1.add(TextPassword);
        TextPassword.setBounds(351, 263, 223, 20);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(351, 301, 223, 20);

        btnConfirmer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnConfirmer.setText("Confirmer");
        btnConfirmer.setPreferredSize(new java.awt.Dimension(70, 25));
        btnConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmerActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmer);
        btnConfirmer.setBounds(450, 450, 100, 25);

        btnRetour.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnRetour.setText("Retour");
        btnRetour.setPreferredSize(new java.awt.Dimension(93, 25));
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetour);
        btnRetour.setBounds(600, 450, 90, 25);

        LabelNum.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        LabelNum.setForeground(new java.awt.Color(255, 255, 255));
        LabelNum.setText("Num_telephone");
        jPanel1.add(LabelNum);
        LabelNum.setBounds(120, 342, 150, 22);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(351, 153, 90, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirmer votre mot de passe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 304, 240, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgroundjdid.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(900, 430));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 817, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        // TODO add your handling code here:
        ClientFrame a = new ClientFrame();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmerActionPerformed
        // TODO add your handling code here:
        if ((TextNom.getText().equalsIgnoreCase("") || TextPrenom.getText().equalsIgnoreCase("") || Textbtn.equals("") || TextAge.getText().equalsIgnoreCase("") || TextLogin.getText().equalsIgnoreCase("") || TextPassword.getText().equalsIgnoreCase("") || jPasswordField2.getText().equalsIgnoreCase("")|| TextNum.getText().equalsIgnoreCase("") || TextEmail.getText().equalsIgnoreCase(""))) {
        
            JOptionPane.showMessageDialog(this, "Veuillez compléter les champs à remplir !!");
        } //        else if(!TextAge.getText()) CONTRAINTE SUR L'AGE ET LE NUMERO DE TEL 
        else {
            ClientDAO client = new ClientDAO();

            String Nom = TextNom.getText();
            String Prenom = TextPrenom.getText();
           
           

            int Age = Integer.parseInt(TextAge.getText());
            String Login = TextLogin.getText();
            String Password = TextPassword.getText();
            int Num_Telephone = Integer.parseInt(TextNum.getText());
            String Email = TextEmail.getText();
            String type="";
            Client cl = new Client();
            cl.setNom(Nom);
            cl.setPrénom(Prenom);
            cl.setSexe(type);
            cl.setAge(Age);
            cl.setLogin(Login);
            cl.setPassword(Password);
            cl.setNumTéléphone(Num_Telephone);
            cl.setEmail(Email);

            client.insertClient(cl);
            JOptionPane.showMessageDialog(this, "Inscription réussie");

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(InscriClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(InscriClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(InscriClient.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriClient().setVisible(true);
            }
        });

    }//GEN-LAST:event_btnConfirmerActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void TextAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAgeActionPerformed

        //TODO add your handling code here:

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JLabel LabelNum;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelPrenom;
    private javax.swing.JLabel LabelSexe;
    private javax.swing.JTextField TextAge;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextLogin;
    private javax.swing.JTextField TextNom;
    private javax.swing.JTextField TextNum;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JTextField TextPrenom;
    private javax.swing.ButtonGroup Textbtn;
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnRetour;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
